[package]
name = "pgd_utils"
version = "0.1.0"
edition = "2024"

[lib]
name = "pgd_utils"
crate-type = ["cdylib"]

[dependencies]
rand = "0.9.0"
rayon = "1.10.0"
pyo3 = "0.23.5"
numpy = "0.23.0"

[dev-dependencies]
ndarray = "0.16.1"
lazy_static = "1.5.0"
